### ISSUE TITLE
Issue with Pages containing tables.

### ISSUE THREAD

**Issue by davidrzs** [iommirocks/iommi#398]
We updated iommi earlier and there seems to be an issue with pages that contain tables that we cannot figure out how to solve. We will investigate further but since this might be an iommi related thing we thought we would quickly post it. Do you have any idea what might have caused this and how we can fix it? 

The following is our stack trace: 
```python
Environment:


Request Method: GET
Request URL: http://127.0.0.1:8000/xyz/

Django Version: 4.2
Python Version: 3.10.11
Installed Applications:
['crud.apps.CrudConfig',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'iommi',
 'bootstrap5',
 'reversion']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'iommi.sql_trace.Middleware',
 'iommi.profiling.Middleware',
 'iommi.middleware']



Traceback (most recent call last):
  File "/Users/david/.local/share/virtualenvs/database-a2NsiTzi/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/david/.local/share/virtualenvs/database-a2NsiTzi/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/david/.local/share/virtualenvs/database-a2NsiTzi/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "/Users/david/.local/share/virtualenvs/database-a2NsiTzi/lib/python3.10/site-packages/iommi/base.py", line 49, in view_wrapper
    return view_wrapper.__iommi_target__.bind(request=request).render_to_response()
  File "/Users/david/.local/share/virtualenvs/database-a2NsiTzi/lib/python3.10/site-packages/iommi/declarative/dispatch.py", line 10, in dispatch_defaults_wrapper
    return f(*args, **Namespace(defaults, kwargs))
  File "/Users/david/.local/share/virtualenvs/database-a2NsiTzi/lib/python3.10/site-packages/iommi/part.py", line 174, in render_to_response
    response = HttpResponse(render_root(part=self, **kwargs))
  File "/Users/david/.local/share/virtualenvs/database-a2NsiTzi/lib/python3.10/site-packages/iommi/declarative/dispatch.py", line 10, in dispatch_defaults_wrapper
    return f(*args, **Namespace(defaults, kwargs))
  File "/Users/david/.local/share/virtualenvs/database-a2NsiTzi/lib/python3.10/site-packages/iommi/part.py", line 214, in render_root
    content = part.__html__(**render)
  File "/Users/david/.local/share/virtualenvs/database-a2NsiTzi/lib/python3.10/site-packages/iommi/declarative/dispatch.py", line 10, in dispatch_defaults_wrapper
    return f(*args, **Namespace(defaults, kwargs))
  File "/Users/david/.local/share/virtualenvs/database-a2NsiTzi/lib/python3.10/site-packages/iommi/page.py", line 124, in __html__
    rendered = {
  File "/Users/david/.local/share/virtualenvs/database-a2NsiTzi/lib/python3.10/site-packages/iommi/page.py", line 125, in <dictcomp>
    name: as_html(
  File "/Users/david/.local/share/virtualenvs/database-a2NsiTzi/lib/python3.10/site-packages/iommi/part.py", line 279, in as_html
    return part.__html__()
  File "/Users/david/.local/share/virtualenvs/database-a2NsiTzi/lib/python3.10/site-packages/iommi/declarative/dispatch.py", line 10, in dispatch_defaults_wrapper
    return f(*args, **Namespace(defaults, kwargs))
  File "/Users/david/.local/share/virtualenvs/database-a2NsiTzi/lib/python3.10/site-packages/iommi/table.py", line 2383, in __html__
    assert self.get_visible_rows() is not None
  File "/Users/david/.local/share/virtualenvs/database-a2NsiTzi/lib/python3.10/site-packages/iommi/table.py", line 2108, in get_visible_rows
    self.visible_rows = self.parts.page.rows
  File "/Users/david/.local/share/virtualenvs/database-a2NsiTzi/lib/python3.10/site-packages/iommi/member.py", line 212, in __getattribute__
    return self[name]
  File "/Users/david/.local/share/virtualenvs/database-a2NsiTzi/lib/python3.10/site-packages/iommi/member.py", line 225, in __getitem__
    _force_bind(self, name)
  File "/Users/david/.local/share/virtualenvs/database-a2NsiTzi/lib/python3.10/site-packages/iommi/member.py", line 271, in _force_bind
    bound_member = _declared_members[name].bind(parent=_parent)
  File "/Users/david/.local/share/virtualenvs/database-a2NsiTzi/lib/python3.10/site-packages/iommi/traversable.py", line 213, in bind
    result.on_bind()
  File "/Users/david/.local/share/virtualenvs/database-a2NsiTzi/lib/python3.10/site-packages/iommi/table.py", line 1427, in on_bind
    self.container.tag = evaluate_strict(self.container.tag)
  File "/Users/david/.local/share/virtualenvs/database-a2NsiTzi/lib/python3.10/site-packages/iommi/struct.py", line 47, in __getattribute__
    raise e
  File "/Users/david/.local/share/virtualenvs/database-a2NsiTzi/lib/python3.10/site-packages/iommi/struct.py", line 39, in __getattribute__
    return object.__getattribute__(self, item)

Exception Type: AttributeError at /xyz/
Exception Value: 'Namespace' object has no attribute 'tag'
```

**Comment by boxed** [comment]
hmm. strange. It looks to me like https://github.com/iommirocks/iommi/blob/master/iommi/table.py#L1743 creates that default, so you should get it. 

Do you perhaps have a custom Style defined? If so, can you show the code?

**Comment by boxed** [comment]
oh, and can you show the code you have for that view?

**Comment by davidrzs** [comment]
You are right, very sorry for this. It was indeed a problem with the style. We copied your bootstrap style and swapped out the CDNs but we forgot to update it. Sorry for this. THanks for your very quick reply!!

**Comment by boxed** [comment]
Hmm. not sure I understand what the problem really was still. Anyway, if you want to use the bootstrap style but change the CDNs you should do something like:

```py
my_style = Style(
    bootstrap,
    root__assets=dict(
        css=Asset.css(
            attrs=dict(
                href='https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css',
                integrity='sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh',
                crossorigin='anonymous',
            ),
        ),
        popper_js=Asset.js(
            attrs=dict(
                src='https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js',
                integrity='sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo',
                crossorigin='anonymous',
            )
        ),
        js=Asset.js(
            attrs=dict(
                src='https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js',
                integrity='sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6',
                crossorigin='anonymous',
            )
        ),
    ),
)
```

**Comment by davidrzs** [comment]
Oh good idea, thanks! Our problem was that we redefined our own bootstrap style quite a while back and we did not keep the style updated. Our code follows exactly your examples on the documentations.
